TESTS WITH ERRORS 
test07 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 127, in test07
    th.read('puzzle8_top_right_empty.txt')
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/game_masters.py", line 28, in read
    for fr in read_tokenize(final_path):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/read.py", line 23, in read_tokenize
    for line in file:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 168: invalid start byte

test08 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 136, in test08
    p8.read('puzzle8_top_right_empty.txt')
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/game_masters.py", line 28, in read
    for fr in read_tokenize(final_path):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/read.py", line 23, in read_tokenize
    for line in file:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 168: invalid start byte

test09 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 156, in test09
    th.read('puzzle8_center_empty.txt')
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/game_masters.py", line 28, in read
    for fr in read_tokenize(final_path):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/read.py", line 23, in read_tokenize
    for line in file:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 168: invalid start byte

test10 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 167, in test10
    p8.read('puzzle8_center_empty.txt')
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/game_masters.py", line 28, in read
    for fr in read_tokenize(final_path):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/read.py", line 23, in read_tokenize
    for line in file:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 168: invalid start byte

-------------------------------
TESTS FAILED  
-------------------------------
TESTS SKIPPED 
-------------------------------
